<?php
  $key=array("miiiosfcoficiai" => array ( "consumer" => "XGd6ShWNvetQkvm46zL2w",
                                          "consumer_secret" => "PozHGrmiqU5Kun8DOFTjRvxweadnhxfZdl5B0PUsns",
                                          "token" => "1190902069-qfNAasEgtoSY25bUj1CpPlDfGj4mKa61SAOUVnQ",
                                          "token_secret" => "DQHLjjGTlA4J2ksCz1OCFqezIyW51D1IbHgzzzJBgW8"
                                         ),
             "miiiosfcoficial" => array ( "consumer" => "0RrWFKuQJvxkmWb145Cg",
                                          "consumer_secret" => "9tVKbw9gINjROEyIGTt4UPHow77qsgXM7ZoTcKARBrc",
                                          "token" => "1190869796-CZKJGeDJObepnZB2TnnDT0sZmZ8XFgm71qeYoUN",
                                          "token_secret" => "GpZYteBTOPJspk49qji20CO2oDfKc5aRUdUsiQ4HUh0"
                                         ),
             "miilosfcoficiai" => array ( "consumer" => "OZur9Hmv0FaEnHHlojyg",
                                          "consumer_secret" => "BdPNfNJw5eMfyXsB3MAKXX8wsA2aucOJ0N3yqSwAdE",
                                          "token" => "1190944106-7qM3x8weDtuZG8Iq9PgOGpFWQLKBYepYWWXWMi6",
                                          "token_secret" => "AMQjCirwRhbyzKuwtByMovjaKXzYygKAUnt2X6ryE"
                                         ),
             "miilosfcoficial" => array ( "consumer" => "H386cst9ycWzihhhotg",
                                          "consumer_secret" => "B6wvfeelKUEoZZyCJgHJBCKEYkS9oKzU0ImOdgMBuY",
                                          "token" => "1190453004-AjNklbwjFR3TKUP2hLWp3Jm9vNaxipsTArbjZWG",
                                          "token_secret" => "GNjGpTAPy2vTxTiMDCdo8z1tbnodrGueKvXNrHndA"
                                         ),                                 
             "miliosfcoficiai" => array ( "consumer" => "adseZAES7R6PRHsGouCuw",
                                          "consumer_secret" => "l9Mxjd9wZ4wmRmDwsutJkq5E6HoS6VG646WrNAYNRKg",
                                          "token" => "	1190894544-el9gvksGDfw9KTgq9G4e2et3GrxGoARfdTzCNmg",
                                          "token_secret" => "WmCIyuvo54A2Opj2WZrUKCfFKndpBVj8aEcwVsNjIcM"
                                         ),   
             "miliosfcoficial" => array ( "consumer" => "Pa8bFQFHAuW9yHFcpb3t0Q",
                                          "consumer_secret" => "QEtCD4xDysS4LdajcSZAvubIxgVxhEYDikJMQcsbyI",
                                          "token" => "1190844458-zb0XPDC4I05O5JppJGo8VtuCOUXj7aoatquFZaQ",
                                          "token_secret" => "k53P323mzMwD6dvxwJ2fuFbtyu3Yz494wnFmZqC3w"
                                         ),
             "millosfcoficiai" => array ( "consumer" => "yT5b7dwHNVnXN6AeGmHQ",
                                          "consumer_secret" => "926oMjnwGRWRAdIcEtOmmsuQihNuNauOi6fwbnDU",
                                          "token" => "1190864209-k3sc6EvtXuTeFLsqQGXqtACnOvCafPIaCpjkRhi",
                                          "token_secret" => "vj7QsVeSLd5iIoSbCdjNbNgZuQW03J7yWewMcx8EgQ"
                                         )   
                                         
                                                                       
            )
?>